name: "e2e"
on: [workflow_dispatch]
jobs:
  test-e2e:
    runs-on: windows-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4
      - name: Installs nodeJS
        uses: actions/setup-node@v2
      - name: Install dependencies
        run: npm ci
      - name: Install Playwright
        run: npx playwright install --with-deps
      - name: Run your tests
        run: npx playwright test tests/home.spec.ts
        #Test results part is not generating/passing correct json file for allure report.
        #Needs to be fixed and  a deeper investigation why
      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: TestResults
          path: test-results

    

